[package]
name = "crux_time"
description = "Time capability for use with crux_core"
version = "0.4.1"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
crux_core = { version = "0.7", path = "../crux_core" }
serde = { workspace = true, features = ["derive"] }
chrono = { version = "0.4.38", features = ["serde"], optional = true }
thiserror = "1.0.60"

[dev-dependencies]
serde_json = "1.0.117"
