[package]
name = "crux_time"
description = "Time capability for use with crux_core"
version = "0.1.0"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
crux_core = { path = "../crux_core", version = "0.2" }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
crux_macros = { version = "0.1", path = "../crux_macros" }
