[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
anyhow.workspace = true
bincode = "1.3.3"
chrono = { version = "0.4.38", features = ["serde"] }
crux_core = { workspace = true }
crux_http = { workspace = true }
crux_kv = { workspace = true }
crux_platform = { workspace = true }
crux_time = { workspace = true }
derive_more = "0.99.17"
lazy_static = "1.4.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.60"
uniffi = "0.27.1"
url = "2.5.0"
wasm-bindgen = "0.2.92"

[dev-dependencies]
assert_let_bind = "0.1.1"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.27.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.27.1", features = ["build"] }
