name = "Notes"
description = "A simple note taking app that syncs across instances using CRDTs"
authors = ["Red Badger Consulting Limited"]
repository = "https://github.com/redbadger/crux/"

[cores.shared]
source = "shared"
type_gen = "shared_types"
crux_version = "0.6.3"

[shells.iOS]
template = "ios"
source = "iOS"
cores = ["shared"]

[shells.web_nextjs]
template = "nextjs"
source = "web-nextjs"
cores = ["shared"]
