[package]
name = "crux_core"
description = "Cross-platform app development in Rust"
authors = ["Red Badger Consulting Limited"]
repository = "https://github.com/redbadger/crux/"
version = "0.1.1"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
keywords = ["crux", "crux_core", "cross-platform-ui", "ffi", "wasm"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
anyhow = "1.0.66"
bcs = "0.1.4"
derive_more = "0.99.17"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
serde-generate = { version = "0.24.0", optional = true }
serde-reflection = { version = "0.3.6", optional = true }
thiserror = "1.0.37"
uniffi = "0.21.0"
uniffi_macros = "0.21.0"
uuid = { version = "1.2.1", features = ["v4", "wasm-bindgen", "js"] }
wasm-bindgen = "0.2.83"

[features]
typegen = ["dep:serde-generate", "dep:serde-reflection"]
