[package]
name = "crux_core"
description = "Cross-platform app development in Rust"
version = "0.7.0"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[features]
typegen = ["dep:serde-generate", "dep:serde-reflection"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
anyhow.workspace = true
bincode = "1.3.3"
crossbeam-channel = "0.5.11"
derive_more = "0.99.17"
futures = "0.3.30"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.111"
serde-generate = { version = "0.25.1", optional = true }
serde-reflection = { version = "0.3.6", optional = true }
thiserror = "1.0.56"
uuid = { version = "1.6.1", features = ["v4", "wasm-bindgen", "js", "serde"] }
wasm-bindgen = "0.2.89"

[dev-dependencies]
assert_fs = "1.0.13"
assert_matches = "1.5"
async-channel = "2.1"
crux_macros = { version = "0.3", path = "../crux_macros" }
crux_http = { version = "0.4", path = "../crux_http" }
crux_time = { version = "0.1", path = "../crux_time" }
serde = { version = "1.0.195", features = ["derive"] }
static_assertions = "1.1"
rand = "0.8"
url = "2.5.0"
