[workspace]
members = ["cli", "shared", "shared_types", "web-yew"]
resolver = "1"

[workspace.package]
authors = ["Red Badger Consulting Limited"]
edition = "2021"
repository = "https://github.com/redbadger/crux/"
license = "Apache-2.0"
keywords = ["crux", "crux_core", "cross-platform-ui", "ffi", "wasm"]
rust-version = "1.66"

[workspace.dependencies]
anyhow = "1.0.79"
crux_core = { version = "0.7", path="../../crux_core" }
crux_http = { version = "0.5", path="../../crux_http" }
crux_kv = { version = "0.1", path="../../crux_kv" }
crux_macros = { version = "0.3", path="../../crux_macros" }
crux_platform = { version = "0.1", path="../../crux_platform" }
crux_time = { version = "0.2", path="../../crux_time" }
serde = "1.0.196"

[workspace.metadata.bin]
cargo-xcode = { version = "=1.7.0" }
