[package]
name = "web-dioxus"
version = "0.1.0"
authors = ["Stuart Harris <stuart.harris@red-badger.com>"]
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
dioxus = "0.4"
dioxus-logger = "0.4.1"
dioxus-web = "0.4"
futures-util = "0.3.28"
log = "0.4.20"
shared = { path = "../shared" }
