[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen", "crux_http/typegen"]

[dependencies]
async-sse = "5.1.0"
async-std = "1.12.0"
chrono = { version = "0.4.38", features = ["serde"] }
crux_core.workspace = true
crux_http.workspace = true
futures = "0.3.30"
lazy_static = "1.5.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.118"
uniffi = "0.28.0"
url = "2.5.2"
wasm-bindgen = "0.2.92"

[dev-dependencies]
assert_let_bind = "0.1.1"
insta = { version = "1.39.0", features = ["yaml"] }

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.28.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }
