[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[dependencies]
anyhow = "1.0.66"
bincode = "1.3.3"
chrono = "0.4.23"
crux_core = { path = "../../../crux_core" }
crux_http = { path = "../../../crux_http" }
crux_macros = { path = "../../../crux_macros" }
derive_more = "0.99.17"
lazy_static = "1.4.0"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.89"
thiserror = "1.0.37"
uniffi = "0.22.0"
uniffi_macros = "0.22.0"
url = "2.3.1"
uuid = { version = "1.2.2", features = ["v4", "wasm-bindgen", "js"] }
wasm-bindgen = "0.2.83"

[build-dependencies]
uniffi_build = { version = "0.22.0", features = ["builtin-bindgen"] }
