[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
anyhow.workspace = true
async-sse = "5.1.0"
async-std = "1.12.0"
bincode = "1.3.3"
chrono = { version = "0.4.26", features = ["serde"] }
crux_core = { version = "0.6", path = "../../../crux_core" }
crux_http = { version = "0.4", path = "../../../crux_http" }
crux_macros = { version = "0.3", path = "../../../crux_macros" }
derive_more = "0.99.17"
futures = "0.3.28"
lazy_static = "1.4.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.103"
thiserror = "1.0.44"
uniffi = "0.24.2"
url = "2.4.0"
wasm-bindgen = "0.2.87"

[dev-dependencies]
assert_let_bind = "0.1.1"
insta = { version = "1.31.0", features = ["yaml"] }

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.24.2", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.24.2", features = ["build"] }
