[package]
name = "shared_types"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]

[build-dependencies]
anyhow.workspace = true
crux_core = { workspace = true, features = ["typegen"] }
crux_http = "0.9"
shared = { path = "../shared", features = ["typegen"] }
