[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[dependencies]
crux_core = { path = "../../../crux_core" }
crux_macros = { path = "../../../crux_macros" }
serde = { workspace = true, features = ["derive"] }
