[package]
name = "crux_http"
description = "HTTP capability for use with crux_core"
version = "0.4.5"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1.77"
crux_core = { version = "0.7", path = "../crux_core" }
crux_macros = { version = "0.3", path = "../crux_macros" }
derive_builder = "0.12.0"
futures-util = "0.3"
http-types = { version = "2.12", default-features = false, features = ["fs"] }
pin-project-lite = "0.2.13"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.111"
url = "2.5.0"

[dev-dependencies]
assert_fs = "1.0.13"
futures-test = "0.3"
assert_matches = "1.5"
crux_core = { version = "0.7", path = "../crux_core", features = ["typegen"] }
