[package]
name = "crux_http"
description = "HTTP capability for use with crux_core"
version = "0.1.0"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1.59"
bcs.workspace = true
crux_core = { version = "0.2", path = "../crux_core" }
derive_more = "0.99.17"
futures-util = "0.3"
http-types = { version = "2.12", no-default-features = true }
pin-project-lite = "0.2.9"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.91"
url = "2.3.1"

[dev-dependencies]
assert_matches = "1.5"
crux_macros = { version = "0.1", path = "../crux_macros" }