[package]
name = "crux_http"
description = "HTTP capability for use with crux_core"
version = "0.8.0"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1.77"
crux_core = { version = "0.7", path = "../crux_core" }
derive_builder = "0.13.0"
futures-util = "0.3"
http-types = { package = "http-types-red-badger-temporary-fork", version = "2.12.0", default-features = false }
pin-project-lite = "0.2.13"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.56"
url = "2.5.0"

[dev-dependencies]
assert_fs = "1.0.13"
futures-test = "0.3"
assert_matches = "1.5"
