[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.1"
futures = "0.3.29"
futures-signals = "0.3.33"
rand = "0.8.5"
serde = "1.0.193"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = "0.1.14"
tower-http = { version = "0.5.0", features = ["cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[workspace]

[package.metadata.bin]
cargo-xcode = { version = "=1.7.0" }
