[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[dependencies]
uniffi = "0.20.0"
uniffi_macros = "0.20.0"

[build-dependencies]
uniffi_build = { version = "0.20.0", features = ["builtin-bindgen"] }
