[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[dependencies]
thiserror = "1.0.37"
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "c00230a1" }
uniffi_macros = { git = "https://github.com/mozilla/uniffi-rs", rev = "c00230a1" }

[build-dependencies]
uniffi_build = { git = "https://github.com/mozilla/uniffi-rs", rev = "c00230a1", features = [
  "builtin-bindgen"
] }
