[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[dependencies]
anyhow = "1.0.65"
futures = "0.3.24"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
thiserror = "1.0.37"
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "c00230a1" }
uniffi_macros = { git = "https://github.com/mozilla/uniffi-rs", rev = "c00230a1" }
ureq = { version = "2.5.0", features = ["json"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
minreq = { version = "2.6.0", features = ["json-using-serde", "https-rustls"] }

[build-dependencies]
uniffi_build = { git = "https://github.com/mozilla/uniffi-rs", rev = "c00230a1", features = [
  "builtin-bindgen"
] }
