[package]
name = "sse"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
async-sse = "5.1.0"
async-std = "1.12.0"
crux_core = { version = "0.2", path = "../../../crux_core" }
crux_macros = { version = "0.1", path = "../../../crux_macros" }
futures = "0.3.25"
serde = { workspace = true, features = ["derive"] }
