[package]
name = "crux_macros"
description = "Macros for use with crux_core"
version = "0.3.7"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.8"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = "2.0.52"

[dev-dependencies]
crux_core = { path = "../crux_core" }
crux_http = { path = "../crux_http" }
insta = "1.36"
prettyplease = "0.2"
serde = { version = "1.0.197", features = ["derive"] }
