[package]
name = "crux_macros"
description = "Macros for use with crux_core"
authors = ["Red Badger Consulting Limited"]
repository = "https://github.com/redbadger/crux/"
version = "0.3.6"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
keywords = ["crux", "crux_core", "cross-platform-ui", "ffi", "wasm"]
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.3"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = "2.0.48"

[dev-dependencies]
crux_core = { version = "0.7", path = "../crux_core" }
crux_http = { version = "0.4", path = "../crux_http" }
insta = "1.34"
prettyplease = "0.2"
serde = { version = "1.0.195", features = ["derive"] }
