[book]
authors = ["Viktor Charypar"]
language = "en"
multilingual = false
src = "src"
title = "Crux: Cross-platform app development in Rust"

[output.html]
mathjax-support = true
site-url = "/crux/"
git-repository-url = "https://github.com/redbadger/crux/"
edit-url-template = "https://github.com/redbadger/crux/edit/master/docs/{path}"
