[package]
name = "crux_kv"
description = "Key-Value capability for use with crux_core"
version = "0.4.1-rc.2"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
crux_core = { version = "0.8.0-rc.2", path = "../crux_core" }
serde = { workspace = true, features = ["derive"] }
thiserror = "1.0.61"
