name: build

on:
  push:
  pull_request:
    branches:
      - master

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: short
  NEXTEST_PROFILE: ci
  CI: 1
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest
    if:
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.11

      - name: Build crux
        shell: bash
        run: cargo build --workspace

      - name: Install nextest
        shell: bash
        run: |
          set -euxo pipefail
          curl -LsSf https://get.nexte.st/0.9/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      # The counter example uses tauri, which has additional dependencies
      - name: Install tauri dependencies
        shell: bash
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            libayatana-appindicator3-dev \
            libgtk-3-dev \
            librsvg2-dev \
            libssl-dev \
            libwebkit2gtk-4.0-dev \
            wget

      - name: Run all tests
        shell: bash
        run: |
          ./scripts/test.sh
