name: build

on:
  push:
  pull_request:
    branches:
      - master

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: short
  NEXTEST_PROFILE: ci
  CI: 1
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest

    if:
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name

    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.11

      - name: Build crux
        shell: bash
        run: cargo build --workspace

      - name: Install nextest
        shell: bash
        run: |
          set -euxo pipefail
          curl -LsSf https://get.nexte.st/0.9/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Run tests
        shell: bash
        run: |
          ./scripts/test.sh

  examples:
    runs-on: ubuntu-latest
    container: ivangabriele/tauri:debian-bookworm-18

    if:
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v3

      - name: Install rustfmt
        shell: bash
        run: rustup component add rustfmt

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install nextest
        shell: bash
        run: |
          set -euxo pipefail
          curl -LsSf https://get.nexte.st/0.9/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Build and Test examples
        shell: bash
        run: |
          ./scripts/build_and_test_examples.sh
