[package]
name = "shared"
version = "0.1.0"
# FIXME - wasm-pack doesn't like these. Re-enable when it does
# authors.workspace = true
# repository.workspace = true
edition.workspace = true
# license.workspace = true
# keywords.workspace = true
rust-version.workspace = true

[features]
typegen = ["crux_core/typegen"]

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { workspace = true, features = ["derive"] }
crux_core.workspace = true
crux_kv.workspace = true
lazy_static = "1.4"
uniffi = "0.27.1"
automerge = "0.4.1"
futures = "0.3"
wasm-bindgen = "0.2"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.27.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.27.1", features = ["build"] }

[dev-dependencies]
assert_let_bind = "0.1.1"
